export const AmminitiesRentResidentialFields = [
    { name: "Swimming Pool", fieldName: "swimmingPool" },
    { name: "Gym", fieldName: "gym" },
    { name: "Parking", fieldName: "parking" },
    { name: "Elevator", fieldName: "elevator" },
    { name: "Security", fieldName: "security" },
    { name: "Power Backup", fieldName: "powerBackup" },
    { name: "Wi-Fi", fieldName: "wifi" },
    { name: "Air Conditioning", fieldName: "airConditioning" },
    { name: "Heating", fieldName: "heating" },
    { name: "Balcony", fieldName: "balcony" },
    { name: "Garden", fieldName: "garden" },
    { name: "Playground", fieldName: "playground" },
    { name: "Community Hall", fieldName: "communityHall" },
    { name: "Clubhouse", fieldName: "clubhouse" },
    { name: "Jogging Track", fieldName: "joggingTrack" },
    { name: "Sports Facilities", fieldName: "sportsFacilities" },
    { name: "Home Automation", fieldName: "homeAutomation" },
    { name: "Intercom", fieldName: "intercom" },
    { name: "Maintenance Staff", fieldName: "maintenanceStaff" },
    { name: "Rainwater Harvesting", fieldName: "rainwaterHarvesting" },
    { name: "Fire Safety", fieldName: "fireSafety" },
    { name: "Waste Disposal", fieldName: "wasteDisposal" },
    { name: "Library", fieldName: "library" },
    { name: "Reserve Parking", fieldName: "reserveParking" },
    { name: "Visitor Parking", fieldName: "visitorParking" },
    { name: "Pet Friendly", fieldName: "petFriendly" },
    { name: "Servant Room", fieldName: "servantRoom" },
    { name: "Internet", fieldName: "internet" },
    { name: "TV Cable", fieldName: "tvCable" },
    { name: "Water Purifier", fieldName: "waterPurifier" },
    { name: "Lift", fieldName: "lift" },
    { name: "Penthouse", fieldName: "penthouse" },
  ];
  
export const AmminitiesRentCommercialFields = [
    { name: "Conference Room", fieldName: "conferenceRoom" },
    { name: "Café", fieldName: "cafe" },
    { name: "Pantry", fieldName: "pantry" },
    { name: "Reception", fieldName: "reception" },
    { name: "Loading Docks", fieldName: "loadingDocks" },
    { name: "High-Speed Internet", fieldName: "highSpeedInternet" },
    { name: "CCTV", fieldName: "cctv" },
    { name: "Fire Alarm", fieldName: "fireAlarm" },
    { name: "Emergency Exit", fieldName: "emergencyExit" },
    { name: "Continuous Water Supply", fieldName: "continuousWaterSupply" },
    { name: "Central Heating", fieldName: "centralHeating" },
    { name: "Central Cooling", fieldName: "centralCooling" },
    { name: "Mail Room", fieldName: "mailRoom" },
    { name: "Server Room", fieldName: "serverRoom" },
    { name: "Business Lounge", fieldName: "businessLounge" },
    { name: "Multi-Level Parking", fieldName: "multiLevelParking" },
  ];

  
export const AmminitiesRentLandFields = [
    { name: "Electricity Connection", fieldName: "electricityConnection" },
    { name: "Water Supply", fieldName: "waterSupply" },
    { name: "Sewage Connection", fieldName: "sewageConnection" },
    { name: "Fencing", fieldName: "fencing" },
    { name: "Road Access", fieldName: "roadAccess" },
    { name: "Gated Access", fieldName: "gatedAccess" },
    { name: "Irrigation", fieldName: "irrigation" },
    { name: "Zoning Approval", fieldName: "zoningApproval" },
    { name: "Drainage System", fieldName: "drainageSystem" },
    { name: "Site Office", fieldName: "siteOffice" },
    { name: "Landscaping", fieldName: "landscaping" },
    { name: "Borewell", fieldName: "borewell" },
    { name: "Street Lighting", fieldName: "streetLighting" },
    { name: "Perimeter Wall", fieldName: "perimeterWall" },
    { name: "Easement", fieldName: "easement" },
  ];

export const AmminitiesRentPGFields = [...AmminitiesRentCommercialFields]